[package]
name = "godust"
version = "0.1.0"
authors = ["d1hasib <d1hasib@yahoo.com>"]
edition = "2018"
description = "Godot project generation tool for the Rustaceans"
readme = "README.md"
repository = "https://github.com/d1hasib/godust/"
license = "MIT"

[dependencies]
structopt = "0.3"
